// Mocks generated by Mockito 5.4.2 from annotations
// in payment_reminder_app/test/data/repositories/budget_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:payment_reminder_app/data/datasources/budget_datasource.dart'
    as _i4;
import 'package:payment_reminder_app/data/datasources/payment_datasource.dart'
    as _i3;
import 'package:payment_reminder_app/data/models/budget_model.dart' as _i7;
import 'package:payment_reminder_app/data/models/budgeting_plan_model.dart'
    as _i8;
import 'package:payment_reminder_app/data/models/category_model.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentDataSource_1 extends _i1.SmartFake
    implements _i3.PaymentDataSource {
  _FakePaymentDataSource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BudgetDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetDataSourceImpl extends _i1.Mock
    implements _i4.BudgetDataSourceImpl {
  @override
  String get user_id => (super.noSuchMethod(
        Invocation.getter(#user_id),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestore),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);
  @override
  _i3.PaymentDataSource get paymentDataSource => (super.noSuchMethod(
        Invocation.getter(#paymentDataSource),
        returnValue: _FakePaymentDataSource_1(
          this,
          Invocation.getter(#paymentDataSource),
        ),
        returnValueForMissingStub: _FakePaymentDataSource_1(
          this,
          Invocation.getter(#paymentDataSource),
        ),
      ) as _i3.PaymentDataSource);
  @override
  _i5.Future<void> editBudgetingPlanFromDataSource(
    String? budgetingPlanId,
    double? startAmount,
    double? targetAmount,
    List<double>? categoryBudgetAmountList,
    List<_i6.CategoryModel>? categoryList,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editBudgetingPlanFromDataSource,
          [
            budgetingPlanId,
            startAmount,
            targetAmount,
            categoryBudgetAmountList,
            categoryList,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> addBudgetingPlanFromDataSource(
    double? startAmount,
    double? targetAmount,
    List<double>? categoryBudgetAmountList,
    List<_i6.CategoryModel>? categoryList,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBudgetingPlanFromDataSource,
          [
            startAmount,
            targetAmount,
            categoryBudgetAmountList,
            categoryList,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<List<_i7.BudgetModel>> getBudgetListFromDataSource(
          String? budgetingPlanId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudgetListFromDataSource,
          [budgetingPlanId],
        ),
        returnValue:
            _i5.Future<List<_i7.BudgetModel>>.value(<_i7.BudgetModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i7.BudgetModel>>.value(<_i7.BudgetModel>[]),
      ) as _i5.Future<List<_i7.BudgetModel>>);
  @override
  _i5.Future<_i8.BudgetingPlanModel?> getBudgetingPlanFromDataSource() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudgetingPlanFromDataSource,
          [],
        ),
        returnValue: _i5.Future<_i8.BudgetingPlanModel?>.value(),
        returnValueForMissingStub: _i5.Future<_i8.BudgetingPlanModel?>.value(),
      ) as _i5.Future<_i8.BudgetingPlanModel?>);
  @override
  _i5.Future<List<_i6.CategoryModel>> getCategoryListFromDataSource() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryListFromDataSource,
          [],
        ),
        returnValue:
            _i5.Future<List<_i6.CategoryModel>>.value(<_i6.CategoryModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i6.CategoryModel>>.value(<_i6.CategoryModel>[]),
      ) as _i5.Future<List<_i6.CategoryModel>>);
}
